var CASES=[
{title:"Price Exploration",tagline:"Turning a non-linear bidding algorithm into a self-service decision tool for insurance media buyers.",tags:["InsurTech","B2B SaaS","Optimization"],stats:[{n:"$8M→$30M+",l:"Monthly media\ninvestment scaled"},{n:"7%",l:"MoM growth in\npolicy binds"},{n:"4",l:"Phases of product\nevolution"}],prev:null,next:1,nextT:"Design System for AI Agents",
sections:[
{lbl:"Context",h:"MarketingOS",body:"MarketingOS is a B2B SaaS platform for top U.S. insurance carriers — helping media buyers manage customer acquisition at scale, handling millions of dollars in weekly ad spend.\n\nInsurance acquisition is expensive and competitive. The relationship between bid price and business outcome is non-linear — a 5% bid increase might generate 1% more leads or 10%. Nobody knows in advance."},
{lbl:"My Role",body:"Sole product designer on a cross-functional team (PM, data scientists, engineers). Owned the feature end-to-end across all 4 phases — from initial concept to final handoff and QA."},
{lbl:"The Problem",h:"Two failure modes",body:"Media buyers were setting bids manually, based on intuition and limited historical data.",bullets:["Overpaying — spending more than necessary on traffic that doesn't convert","Underinvesting — leaving quality traffic on the table by bidding too low","A wrong pricing decision could cost hundreds of thousands of dollars per month"]},
{lbl:"Key Insight",insight:"The algorithm existed. The problem wasn't the math — it was that the output was inaccessible to the people who needed to act on it. The design job was translation: from algorithm output to confident human decision."},
{lbl:"Solution",h:"4 phases of evolution",steps:[{n:"Phase 01",t:"Ad Group Price Exploration",d:"First version: recommendations at the ad group level. Users could see the suggested price change, projected effect on lead volume and CPB, and apply it in one click."},{n:"Phase 02",t:"Bidding Group Optimization",d:"Grouped the same insurance product across multiple traffic sources into Bidding Groups. Recommendations became more statistically significant and aligned to actual business logic."},{n:"Phase 03",t:"Channel Optimization",d:"Different channels respond to price changes differently. Extended the system to channel level — finding the optimal price for each channel's unique characteristics."},{n:"Phase 04",t:"Universal Cohort Exploration",d:"Any cohort the platform supports. Price Exploration transformed from a bid optimization tool into a universal price research platform."}]},
{lbl:"UI Principles",bullets:["Recommendation always paired with projected impact (leads, CPB delta, cost)","Confidence indicators — surface how much data backs the recommendation","One-click apply — no friction between insight and action","Clear separation: what the system found vs. what the user decides"]},
{lbl:"Impact",impacts:[{n:"$30M+",c:"g",l:"Monthly media\ninvestment at scale"},{n:"7%",c:"g",l:"MoM growth in\npolicy binds"},{n:"Days→Min",c:"a",l:"Time from data\nto decision"},{n:"4×",c:"b",l:"Optimization\ngranularity levels"}]},
{lbl:"Reflection",reflection:"This was the project that taught me what it means to design for high-stakes decisions under uncertainty. The algorithm could tell you what it found — but it couldn't tell the user how much to trust it. Designing that trust layer was harder than any interaction pattern.\n\n<strong>You can't simplify what you don't deeply understand.</strong> I spent weeks learning insurance acquisition metrics before I could design anything useful."}
]},
{title:"Design System for AI Agents",tagline:"I built a design system. Then AI agents tried to implement it — and I had to rebuild it for them.",tags:["Design Systems","AI-native","Figma"],stats:[{n:"4",l:"Frontend engineers\nusing agentic tools"},{n:"↓",l:"AI clarification\ncycles reduced"},{n:"✦",l:"Replicable model\nfor AI-ready DS"}],prev:0,prevT:"Price Exploration",next:2,nextT:"AI Data Assistant",
sections:[
{lbl:"Context",body:"Kissterra's engineering team adopted AI-agent-driven development — using Cursor and Claude Code to implement features directly from Figma. I had built the design system from scratch, establishing the component library, design tokens, and visual language. It worked well for human developers. Then we tried it with AI agents."},
{lbl:"The Problem",h:"Complete. But not machine-readable.",body:"AI coding agents are not experienced developers. An experienced developer draws on years of pattern recognition — they know implicitly when to use a Tooltip vs. a Popover. An AI agent only knows what it can read.",bullets:["Wrong component choices for similar-looking UI patterns","Missing edge cases and states in implementation","Long clarification loops between engineers and AI","Inconsistencies that slipped through to production"]},
{lbl:"Key Insight",insight:"Documentation in design systems has always been written for humans who can infer, ask questions, and apply judgment. AI agents need explicit, structured, unambiguous context available at the exact moment of implementation."},
{lbl:"Solution",h:"A two-layer context system",steps:[{n:"Layer 01",t:"Context in Figma",d:"Every component got embedded documentation — structured annotations in Figma: what it is, when to use, when NOT to use, all states, edge cases, Do/Don't. Structured enough for an agent to parse reliably."},{n:"Layer 02",t:"component-doc.md in the repo",d:"Each component got a corresponding Markdown file in the codebase — the same information, living alongside the code. Always current, always accessible to the agent's context window."},{n:"Layer 03",t:"Supporting tooling",d:"Figma ↔ repo sync to detect component changes, diff detection to surface what changed, and structured prompts to generate first-draft docs for new components."}]},
{lbl:"Architecture",diagram:"Figma (design source)        Repository (implementation)\n├── Component visuals          ├── Component code\n├── All states & variants      ├── component-doc.md\n└── Embedded context docs  ←→  └── Always in sync\n          ↑\n    AI agent reads both\n    during implementation"},
{lbl:"Impact",impacts:[{n:"↓↓",c:"g",l:"AI clarification\ncycles reduced"},{n:"↑",c:"g",l:"Code generation\nquality improved"},{n:"Day 1",c:"a",l:"New components ship\nwith docs"},{n:"4",c:"b",l:"Engineers benefit\ndirectly"}]},
{lbl:"Reflection",reflection:"This project changed how I think about design systems entirely. A design system isn't just a library of components — it's a shared language. As consumers expand to include machines, the language has to become more explicit.\n\n<strong>Documentation is design.</strong> The time I spent writing component docs wasn't maintenance work — it was product work. The quality of those docs directly determined the quality of what got built."}
]},
{title:"AI Data Assistant",tagline:"Designing a conversational co-pilot where the hard part isn't the chat UI — it's making AI decisions trustworthy enough to act on.",tags:["Conversational UX","Agentic Design","AX"],stats:[{n:"3",l:"Phases from suggest\nto autonomous action"},{n:"↓",l:"Time-to-insight\nfor media buyers"},{n:"✦",l:"AX pattern library\nfor the platform"}],prev:1,prevT:"Design System for AI Agents",next:3,nextT:"Cross-Campaign Management",
sections:[
{lbl:"Context",body:"Media buyers using MarketingOS spend significant time manually navigating dashboards to answer basic questions: Which channels are underperforming? Where should I shift budget? What's driving that CPB spike?\n\nThe data exists. The problem is access — finding the right numbers requires knowing where to look, how to filter, and how to interpret. For complex situations, this could take hours."},
{lbl:"The Problem",h:"Building trust for high-stakes decisions",body:"Building a chat interface is straightforward. Building one that people trust for decisions that move hundreds of thousands of dollars in ad spend is not.",bullets:["Trust — how does the user know the AI's answer is accurate?","Explainability — why is the system recommending this specific action?","Appropriate confidence — how to communicate uncertainty without undermining usefulness?","Human-in-the-loop — how to design the moment between 'AI suggests' and 'user acts'?","Progressive autonomy — how does the product evolve toward autonomous execution?"]},
{lbl:"Key Insight",insight:"Most conversational UX frameworks assume the AI is answering questions. This product needed to go further — toward recommendations, and eventually toward action. The architecture had to support all three modes — and be honest with the user about which mode they're in."},
{lbl:"Response Architecture",steps:[{n:"Mode 01",t:"Data query response",d:"Table or summary card + source reference + time range. Accuracy and transparency are the primary design values."},{n:"Mode 02",t:"Recommendation response",d:"Suggested action + projected impact + confidence level + Apply / Dismiss. All supporting data visible by default."},{n:"Mode 03",t:"Executed action response",d:"Confirmation + what changed + Undo option. Full audit trail, every AI-executed change timestamped and attributable."}]},
{lbl:"Progressive Autonomy",steps:[{n:"Phase 1 — Shipped",t:"Read-only assistant",d:"Query data, get analysis, receive recommendations. User executes manually. Build trust before giving AI agency."},{n:"Phase 2 — Designed",t:"Assisted execution",d:"User approves AI recommendations with one click. AI executes. The approval patterns from Phase 1 make this feel like a natural progression."},{n:"Phase 3 — Vision",t:"Autonomous mode",d:"AI acts within user-defined guardrails, surfaces a digest of actions taken. Users opt in — trust is earned, not assumed."}]},
{lbl:"Impact",impacts:[{n:"↓",c:"g",l:"Time from data to\nactionable insight"},{n:"3",c:"a",l:"Phases of product\nevolution designed"},{n:"↑",c:"b",l:"Foundation for\nautonomous campaign mgmt"},{n:"✦",c:"g",l:"Reusable AX\npattern library"}]},
{lbl:"Reflection",reflection:"This was the most conceptually challenging project I've worked on. Not because of interaction complexity, but because of the fundamental question: <strong>how do you design for appropriate trust?</strong>\n\nToo much trust in AI is dangerous — users stop thinking critically. Too little and the product becomes useless. The design job was finding the calibration.\n\nDesigning AI products requires thinking about failure states as carefully as success states. What does the UI show when the AI is uncertain? When it made a mistake? These are design decisions, not engineering footnotes."}
]},
{title:"Cross-Campaign Management",tagline:"When media buyers manage hundreds of campaigns simultaneously, one-by-one editing isn't a UX problem — it's a business blocker.",tags:["Workflow Design","Bulk Editing","B2B SaaS"],stats:[{n:"Hours→Min",l:"Time for large-scale\ncampaign updates"},{n:"3",l:"Subsequent features\nbuilt on this foundation"},{n:"✦",l:"Self-service for\npreviously manual ops"}],prev:2,prevT:"AI Data Assistant",next:4,nextT:"Channel Analysis",
sections:[
{lbl:"Context & Problem",h:"One-by-one editing at enterprise scale",body:"MarketingOS users manage complex campaign structures — multiple campaigns, each with ad groups, channels, and targeting segments. Making a strategic change required editing each campaign individually. For large accounts, this was hours of repetitive work and a major source of errors."},
{lbl:"Key Design Challenges",bullets:["Representing selection state across a deeply nested hierarchy","Showing the scope of a pending bulk action before it's applied","Handling mixed states — what happens when selected items have different current values?","Confirmation patterns for irreversible bulk operations"]},
{lbl:"Solution",body:"Redesigned campaign management to support bulk editing across campaigns, ad groups, and channels simultaneously. The feature became the infrastructure layer for subsequent platform capabilities — Channel Groups, Performance Views, and Cross-Campaign Dashboard all built on top of the same selection model."},
{lbl:"Impact",impacts:[{n:"Hours→Min",c:"g",l:"Time for large-scale\nupdates"},{n:"✦",c:"a",l:"Self-service for\nmanual ops"},{n:"3",c:"b",l:"Subsequent features\nbuilt on this"},{n:"↓",c:"g",l:"Manual support\nrequests"}]},
{lbl:"Reflection",reflection:"The most impactful design decisions weren't the visible interactions — they were the selection model and state management patterns that enabled three subsequent features to be built faster and more consistently.\n\n<strong>Good UX infrastructure is invisible. You only notice it when it's missing.</strong>"}
]},
{title:"Channel Analysis & Outlier Detection",tagline:"Surfacing the channels that need attention — before the budget damage is done.",tags:["Data Visualization","Recommendations","B2B SaaS"],stats:[{n:"8+",l:"KPIs tracked per\nchannel"},{n:"14/30d",l:"Performance trends\nfor scoring"},{n:"✦",l:"Foundation for\nautomated execution"}],prev:3,prevT:"Cross-Campaign Management",next:null,
sections:[
{lbl:"Context & Problem",h:"Underperforming channels hiding in plain sight",body:"MarketingOS users run traffic across dozens of channels simultaneously. Identifying which channels are underperforming required manual comparison across tables of data — slow, error-prone, and easy to miss."},
{lbl:"Solution",h:"Three components",steps:[{n:"01",t:"Channel Outlier Highlighting",d:"Algorithmic flagging identifying channels deviating significantly from expected performance. Outliers surfaced with severity levels — users see what needs attention immediately, without scanning every row."},{n:"02",t:"Channel Groups",d:"Channels with similar performance characteristics grouped and optimized together — reducing management surface and enabling coordinated bid changes across related traffic sources."},{n:"03",t:"Recommendations Engine",d:"Each channel receives a scored recommendation based on 14 and 30-day performance trends across 8+ KPIs. Recommendations are explainable — users see the scoring logic, not just the output."}]},
{lbl:"Impact",impacts:[{n:"Instant",c:"g",l:"Outlier detection vs.\nmanual scanning"},{n:"8+",c:"a",l:"KPIs per channel\nrecommendation"},{n:"✦",c:"b",l:"Foundation for\nautomated execution"},{n:"↑",c:"g",l:"Budget reallocation\nquality"}]},
{lbl:"Reflection",reflection:"This project was a lesson in the relationship between data density and cognitive load. Media buyers have a lot of data — the design job wasn't to show more of it, but to surface the signal in the noise.\n\n<strong>The most valuable UX decision was the outlier detection algorithm's visual output</strong> — how to represent severity, confidence, and recommended action in a way a busy media buyer could parse in under three seconds."}
]}
];

var CASE_BG=[
  'linear-gradient(135deg,#0a0f0a 0%,#0d1a0f 40%,#080808 100%)',
  'linear-gradient(135deg,#080d14 0%,#0a1220 40%,#080808 100%)',
  'linear-gradient(135deg,#100a08 0%,#1a0d08 40%,#080808 100%)',
  'linear-gradient(135deg,#0d0a14 0%,#120f1a 40%,#080808 100%)',
  'linear-gradient(135deg,#080d0d 0%,#0a1414 40%,#080808 100%)'
];
