var CASES=[
{title:"Price Exploration",tagline:"Turning a non-linear bidding algorithm into a self-service decision tool for insurance media buyers.",tags:["InsurTech","B2B SaaS","Optimization"],image:"assets/price-exploration/web/image-1.webp",stats:[{n:"7%",l:"MoM growth in\npolicy binds"},{n:"4",l:"Phases of product\nevolution"},{n:"Real-time",l:"Price testing\nacross all segments"}],prev:2,prevT:"AI Data Assistant",next:3,nextT:"Cross-Campaign Management",
sections:[
{lbl:"Context",h:"MarketingOS",body:"MarketingOS is a B2B SaaS platform for top U.S. insurance carriers — helping media buyers manage customer acquisition at scale, handling millions of dollars in weekly ad spend.\n\nInsurance acquisition is expensive and competitive. The relationship between bid price and business outcome is non-linear — a 5% bid increase might generate 1% more leads or 10%. Nobody knows in advance."},
{lbl:"My Role",body:"Sole product designer on a cross-functional team (PM, data scientists, engineers). Owned the feature end-to-end across all 4 phases — from initial concept to final handoff and QA."},
{lbl:"The Problem",h:"Two failure modes",body:"Media buyers were setting bids manually, based on intuition and limited historical data.",bullets:["Overpaying — spending more than necessary on traffic that doesn't convert","Underinvesting — leaving quality traffic on the table by bidding too low","A wrong pricing decision could cost hundreds of thousands of dollars per month"]},
{lbl:"Key Insight",insight:"Before Price Exploration, buyers ran price tests manually — duplicating ad groups, adjusting bids by hand, tracking results across separate views. It worked, but it was slow, impossible to run simultaneously across hundreds of segments, and couldn't keep up with a market that shifts week to week. The design job was to make that process automatic, visual, and real-time. When the client started calling it \"Price Exploration\" in their own messages before we'd even named it, we knew the mental model had landed."},
{lbl:"Solution",h:"4 phases of evolution",steps:[{n:"Phase 01",t:"Ad Group Price Exploration",d:"First version: recommendations at the ad group level. Users could see the suggested price change, projected effect on lead volume and CPB, and apply it in one click."},{n:"Phase 02",t:"Bidding Group Optimization",d:"Grouped the same insurance product across multiple traffic sources into Bidding Groups. Recommendations became more statistically significant and aligned to actual business logic."},{n:"Phase 03",t:"Channel Optimization",d:"Different channels respond to price changes differently. Extended the system to channel level — finding the optimal price for each channel's unique characteristics."},{n:"Phase 04",t:"Universal Cohort Exploration",d:"Any cohort the platform supports. Price Exploration transformed from a bid optimization tool into a universal price research platform."}]},
{lbl:"Phase 01",h:"Ad Group Price Exploration",body:"First live version. Recommendations surfaced at the ad group level within a single campaign — users could see the suggested price change, projected lead volume delta and CPB, and apply it in one click. The feature was opt-in per ad group, giving buyers full control during the trust-building phase.",images:[{src:"assets/price-exploration/web/image-2.webp",alt:"Price Exploration activation for Ad Groups"}]},
{lbl:"Phase 02 — 03",h:"Bidding Group & Channel Optimization",body:"As buyers gained confidence, we expanded the scope. Phase 02 grouped ad groups sharing the same insurance product across traffic sources into Bidding Groups — recommendations became more statistically significant. Phase 03 extended the system to channel level, where each channel's unique response curve required its own price finding.\n\nTwo exploration modes emerged: <strong>Strategies</strong> — preset optimization goals the system follows automatically — and <strong>Custom Testing</strong> — buyer-defined price ranges with manual control. The choice depended on how much trust the business was willing to delegate to the algorithm.",images:[{src:"assets/price-exploration/web/image-3.webp",alt:"Strategies and custom price testing modes"},{src:"assets/price-exploration/web/image-4.webp",alt:"Price testing visualization in Ad Groups and Bidding Optimization"}]},
{lbl:"Phase 04",h:"Cross-Campaign Optimization",body:"Once Cross-Campaign Management shipped its selection model and Bidding Group infrastructure, Price Exploration could operate at a new level. Buyers could now run optimization across Bidding Groups and Channel Groups spanning multiple campaigns simultaneously — a single testing configuration covering the entire account instead of individual ad groups. Management overhead dropped dramatically.",images:[{src:"assets/price-exploration/web/image-5.webp",alt:"Cross-campaign price optimization across Bidding Groups and Channel Groups"}]},
{lbl:"Trust Design",h:"Earning the right to automate",body:"Early on, we explored moving toward automation sooner. Clients pushed back — not because the algorithm was wrong, but because they didn't yet trust it enough to delegate decisions.\n\nThis shaped every design decision: a test readiness indicator showed when a test had enough data to be meaningful; a data volume signal let buyers weigh confidence themselves; daily anomaly alerts flagged when real-time visualization reflected a short-term spike rather than a trend.\n\nThe goal wasn't to hide uncertainty — it was to make uncertainty legible. Auto-pilot modes are now in development. The trust had to come first."},
{lbl:"Screens",carousel:["assets/price-exploration/web/carusel-1.webp","assets/price-exploration/web/carusel-2.webp","assets/price-exploration/web/carusel-3.webp","assets/price-exploration/web/carusel-4.webp","assets/price-exploration/web/carusel-5.webp"]},
{lbl:"Impact",impacts:[{n:"$30M+",c:"g",l:"Monthly media\ninvestment at scale"},{n:"7%",c:"g",l:"MoM growth in\npolicy binds"},{n:"Days→Min",c:"a",l:"Time from data\nto decision"},{n:"4×",c:"b",l:"Optimization\ngranularity levels"}]},
{lbl:"Reflection",reflection:"This was the project that taught me what it means to design for high-stakes decisions under uncertainty. The algorithm could tell you what it found — but it couldn't tell the user how much to trust it. Designing that trust layer was harder than any interaction pattern.\n\n<strong>You can't simplify what you don't deeply understand.</strong> I spent weeks learning insurance acquisition metrics before I could design anything useful."}
]},
{title:"Design System for AI Agents",tagline:"I built a design system. Then AI agents tried to implement it — and I had to rebuild it for them.",tags:["Design Systems","AI-native","Figma"],image:"assets/design-system/web/image-1.webp",stats:[{n:"15→2",l:"Design questions per\nfeature implementation"},{n:"~990",l:"Design tokens\ntracked automatically"},{n:"9",l:"Drift audits in\n16 days"}],prev:4,prevT:"Channel Analysis",next:2,nextT:"AI Data Assistant",
sections:[
{lbl:"Context",body:"Kissterra is a B2B SaaS platform in performance marketing. The product team shipped weekly, and the development workflow was increasingly AI-assisted — code agents scaffolded components from design specs, wrote implementation plans from feature docs, and flagged design inconsistencies during code review.\n\nI had built the design system from scratch: 56 components, ~990 design tokens across three collections, a complete visual language. It worked well for human developers. Then we tried it with AI agents — and the system broke in ways we hadn't anticipated."},
{lbl:"My Role",body:"Design system lead — owned token architecture, component documentation format, and AI workflow design. Built the component library and visual language from scratch. When AI agents exposed structural gaps, I designed the documentation format and built the automated drift detection system."},
{lbl:"The Problem",h:"Built for humans who can infer",body:"The problem wasn't that the design system was bad. It was that it was built for humans.\n\n<strong>Silent drift.</strong> Figma is the source of truth, but nothing connected Figma to documentation. Token renames, property changes, new variants — all invisible until a developer hit them mid-implementation. In an AI-assisted workflow, this breaks silently: an outdated token name translates directly to a wrong CSS variable in generated code.\n\n<strong>Two-audience problem.</strong> Component docs needed to serve two very different readers: AI agents that need compact, parseable structured data — and developers who need rich context about states, interactions, and edge cases. Traditional documentation is optimized for one or the other, rarely both."},
{lbl:"Key Insight",insight:"The first complex component shipped with the original doc format generated 15 design questions during implementation. I categorized them: 8 were behavioral edge cases, 2 were consumer boundary questions, 2 were accessibility strings, and the rest were about tokens and constraints. Each category became a section in the updated format. The next two features generated 2 questions combined — both were product-level copy decisions no spec could answer."},
{lbl:"Doc Format",h:"Designed from failure modes, not best practices",body:"The documentation format wasn't designed speculatively — every section exists because its absence caused specific, documented errors. After analyzing the 15 returned questions from the Analytics Table implementation, I built a format with seven structured sections.",images:[{src:"assets/design-system/web/image-3.webp",alt:"The information gap — 15 questions before the format update, 2 after. Each doc section prevents a specific category of errors."}]},
{lbl:"Solution",h:"A three-layer context system",steps:[{n:"Layer 01",t:"Context in Figma",d:"Every component got a compact structured description (~600 chars): Anatomy, Props with defaults, Token references, Accessibility contract. Parseable by agents, readable by humans. Compact enough for Figma's 2000-char limit."},{n:"Layer 02",t:"component-doc.md in the repo",d:"Rich Markdown specs: Purpose, full Variant API, States table, Behavior section (dismiss matrix for overlays, interaction model for complex controls), Consumer Contract, Token Mapping with full alias resolution to hex, Implementation Rules."},{n:"Layer 03",t:"Automated drift detection",d:"A sync system comparing Figma state against a stored baseline. Risk-classified changes: Critical (token removed, prop renamed) → Low (new token added). Agent detects, human confirms, agent applies. Zero manual sync hours post-baseline."}]},
{lbl:"Two Contracts",h:"One component, two representations",body:"Every component gets a compact Figma description (~600 chars, slash-notation) for agents that need to parse quickly — and a rich Markdown spec for developers who need full context: Variant API, States, Behavior, Token Mapping with resolved hex values, Implementation Rules.\n\nThe formats stay synchronized, but serve different moments. Curated sections (Purpose, Implementation Rules) are preserved across updates — the automation never overwrites handwritten design intent. Generated sections (Variant API, Token Mapping) regenerate from Figma on drift.",images:[{src:"assets/design-system/web/image-4.webp",alt:"Figma component with embedded structured description — compact slash-notation format"},{src:"assets/design-system/web/image-5.webp",alt:"component-doc.md — structured specification with Variant API, Token Mapping, Visual Styles"}]},
{lbl:"Component Library",h:"56 components, every state accounted for",body:"The design system covers the full spectrum: from atomic controls (Button, Checkbox, Switch) to complex composites (Analytics Table, Mega Chart, Date Range Selector, Filter System). Each component fully specified — every size, state, style variant documented and token-mapped.\n\nThe token architecture uses three DTCG-format collections: Primitives (~280 tokens), Semantic (~150), Components (~620). Every alias chain resolved in documentation — making system intent visible rather than hiding it behind raw values.",images:[{src:"assets/design-system/web/image-2.webp",alt:"Button component — full variant matrix: Size × Style × State × Icon × Multiple Actions"}]},
{lbl:"Drift Detection",h:"The system that keeps it honest",body:"Design systems drift. Tokens get renamed, props change, descriptions fall out of date. In an AI-assisted workflow, drift breaks silently — an outdated token name translates directly to a wrong CSS variable in generated code.\n\nThe automated sync system runs audits comparing the live Figma file against a stored baseline. Nine audits across 16 days caught a major token restructuring (7 breaking renames), two components added mid-sprint, and incremental changes from active development. Every change was reviewed before reaching production. No developer discovered a discrepancy before the system did.",images:[{src:"assets/design-system/web/image-6.webp",alt:"TerraUI drift detection — risk-classified audit with real token and component changes"}]},
{lbl:"Impact",body:"After the format update, developer design Q&A dropped from 15 questions per complex feature to 2. New components ship with structured docs from day one. Drift detection, review, and documentation update takes minutes — and scales independently of how fast Figma evolves.",impacts:[{n:"15→2",c:"g",l:"Design questions per\nfeature implementation"},{n:"9",c:"g",l:"Drift audits in\n16 days — all caught"},{n:"0",c:"a",l:"Manual sync hours\npost-baseline"},{n:"4",c:"b",l:"Engineers using\nagentic workflow"}]},
{lbl:"Reflection",reflection:"The most important thing I learned was that documentation quality isn't a writing problem — it's a structural problem. The questions developers returned weren't about missing details within existing sections; they were about missing categories of information. States. Dismiss affordances. Consumer boundaries.\n\n<strong>Documentation is design.</strong> Working in an AI-assisted environment changed how I think about what a component spec is for. It's not just documentation that a human might eventually read — it's a contract parsed at implementation time. Ambiguity that a human fills in from context becomes a real error when an agent fills it in incorrectly."}
]},
{title:"AI Data Assistant",tagline:"Designing a conversational co-pilot where the hard part isn't the chat UI — it's making AI decisions trustworthy enough to act on.",tags:["Conversational UX","Agentic Design","AX"],stats:[{n:"3",l:"Phases from suggest\nto autonomous action"},{n:"↓",l:"Time-to-insight\nfor media buyers"},{n:"✦",l:"AX pattern library\nfor the platform"}],prev:1,prevT:"Design System for AI Agents",next:0,nextT:"Price Exploration",
sections:[
{lbl:"Context",body:"Media buyers using MarketingOS spend significant time manually navigating dashboards to answer basic questions: Which channels are underperforming? Where should I shift budget? What's driving that CPB spike?\n\nThe data exists. The problem is access — finding the right numbers requires knowing where to look, how to filter, and how to interpret. For complex situations, this could take hours."},
{lbl:"The Problem",h:"Building trust for high-stakes decisions",body:"Building a chat interface is straightforward. Building one that people trust for decisions that move hundreds of thousands of dollars in ad spend is not.",bullets:["Trust — how does the user know the AI's answer is accurate?","Explainability — why is the system recommending this specific action?","Appropriate confidence — how to communicate uncertainty without undermining usefulness?","Human-in-the-loop — how to design the moment between 'AI suggests' and 'user acts'?","Progressive autonomy — how does the product evolve toward autonomous execution?"]},
{lbl:"Key Insight",insight:"Most conversational UX frameworks assume the AI is answering questions. This product needed to go further — toward recommendations, and eventually toward action. The architecture had to support all three modes — and be honest with the user about which mode they're in."},
{lbl:"Response Architecture",steps:[{n:"Mode 01",t:"Data query response",d:"Table or summary card + source reference + time range. Accuracy and transparency are the primary design values."},{n:"Mode 02",t:"Recommendation response",d:"Suggested action + projected impact + confidence level + Apply / Dismiss. All supporting data visible by default."},{n:"Mode 03",t:"Executed action response",d:"Confirmation + what changed + Undo option. Full audit trail, every AI-executed change timestamped and attributable."}]},
{lbl:"Progressive Autonomy",steps:[{n:"Phase 1 — Shipped",t:"Read-only assistant",d:"Query data, get analysis, receive recommendations. User executes manually. Build trust before giving AI agency."},{n:"Phase 2 — Designed",t:"Assisted execution",d:"User approves AI recommendations with one click. AI executes. The approval patterns from Phase 1 make this feel like a natural progression."},{n:"Phase 3 — Vision",t:"Autonomous mode",d:"AI acts within user-defined guardrails, surfaces a digest of actions taken. Users opt in — trust is earned, not assumed."}]},
{lbl:"Impact",impacts:[{n:"↓",c:"g",l:"Time from data to\nactionable insight"},{n:"3",c:"a",l:"Phases of product\nevolution designed"},{n:"↑",c:"b",l:"Foundation for\nautonomous campaign mgmt"},{n:"✦",c:"g",l:"Reusable AX\npattern library"}]},
{lbl:"Reflection",reflection:"This was the most conceptually challenging project I've worked on. Not because of interaction complexity, but because of the fundamental question: <strong>how do you design for appropriate trust?</strong>\n\nToo much trust in AI is dangerous — users stop thinking critically. Too little and the product becomes useless. The design job was finding the calibration.\n\nDesigning AI products requires thinking about failure states as carefully as success states. What does the UI show when the AI is uncertain? When it made a mistake? These are design decisions, not engineering footnotes."}
]},
{title:"Cross-Campaign Management",tagline:"When media buyers manage hundreds of campaigns simultaneously, one-by-one editing isn't a UX problem — it's a business blocker.",tags:["Workflow Design","Bulk Editing","B2B SaaS"],image:"assets/cross-campaign/web/image-1.webp",stats:[{n:"Hours→Min",l:"Time for large-scale\ncampaign updates"},{n:"3",l:"Subsequent features\nbuilt on this foundation"},{n:"✦",l:"Self-service for\npreviously manual ops"}],prev:0,prevT:"Price Exploration",next:4,nextT:"Channel Analysis",
sections:[
{lbl:"Context & Problem",h:"One-by-one editing at enterprise scale",body:"MarketingOS users manage complex campaign structures — multiple campaigns, each with ad groups, channels, and targeting segments. Making a strategic change required editing each campaign individually. For large accounts, this was hours of repetitive work and a major source of errors."},
{lbl:"My Role",body:"Sole product designer on a cross-functional team (PM, engineers). Owned the feature end-to-end — from initial concept through prototyping, client feedback iterations, and final handoff."},
{lbl:"Key Insight",insight:"The real design challenge wasn't bulk editing — every team knew that was needed. The challenge was rethinking the campaign as a unit of control. Before Cross-Campaign Management, everything — editing, optimization, analysis — happened inside a single campaign. The insight was to make the campaign just one dimension, not a container. Once that boundary broke, bulk editing wasn't a feature — it was a natural consequence."},
{lbl:"Key Design Challenges",bullets:["Mixed states — when selected items had different current values, inline alerts inside the action modal explained the consequences. For irreversible changes, a secondary confirmation was required.","Scope visibility — for high-impact actions like bid price changes, the modal showed an Estimated Spend Impact summary so buyers could evaluate consequences before applying.","Post-action clarity — changes confirmed via toast message and logged in Change Log, with inline Last Bid Change / Last Modifier visibility directly inside the module."]},
{lbl:"Solution",body:"Redesigned campaign management to support bulk editing across campaigns, ad groups, and channels simultaneously. The feature became the infrastructure layer for subsequent platform capabilities — Channel Groups, Performance Views, and Cross-Campaign Dashboard all built on top of the same selection model.\n\nAll ad groups across every campaign became visible and selectable from a single Ad Groups tab — not just within their parent campaign. Users could assign one ad group, or a bulk selection spanning multiple campaigns, to a shared bidding group, giving the business a single dial to manage bid price for the entire group instead of editing each ad group individually.",images:[{src:"assets/cross-campaign/web/image-2.webp",alt:"Ad Groups — assigning ad groups to a shared bidding group"}]},
	{lbl:"",body:"The table also supported two view modes: a <strong>Flat view</strong> listing every ad group individually, and a <strong>Grouped view</strong> that clustered ad groups by their assigned bidding group — making it far easier to scan and control bid price at the group level. Switching between the two significantly improved both usability and oversight.",images:[{src:"assets/cross-campaign/web/image-3.webp",alt:"Ad Groups table — Flat view and Grouped view modes"}]},
	{lbl:"Screens",carousel:["assets/cross-campaign/web/carusel-1.webp","assets/cross-campaign/web/carusel-2.webp","assets/cross-campaign/web/carusel-3.webp","assets/cross-campaign/web/carusel-4.webp","assets/cross-campaign/web/carusel-5.webp"]},
{lbl:"Impact",impacts:[{n:"Hours→Min",c:"g",l:"Time for large-scale\nupdates"},{n:"✦",c:"a",l:"Self-service for\nmanual ops"},{n:"3",c:"b",l:"Subsequent features\nbuilt on this"},{n:"$30M+",c:"g",l:"Platform media\nscaled — built on\nthis foundation"}]},
{lbl:"Reflection",reflection:"The most impactful design decisions weren't the visible interactions — they were the selection model and state management patterns that enabled three subsequent features to be built faster and more consistently.\n\n<strong>Good UX infrastructure is invisible. You only notice it when it's missing.</strong>"}
]},
{title:"Channel Analysis & Outlier Detection",tagline:"Surfacing the channels that need attention — before the budget damage is done.",tags:["Data Visualization","Recommendations","B2B SaaS"],image:"assets/channel-analysis/web/image-1.webp",stats:[{n:"Weeks→Hours",l:"Time to detect\nchannel degradation"},{n:"2,000+",l:"Channels under\nautomatic monitoring"},{n:"Daily",l:"Frequency of use\nby media buyers"}],prev:3,prevT:"Cross-Campaign Management",next:1,nextT:"Design System for AI Agents",
sections:[
{lbl:"Context & Problem",h:"Underperforming channels hiding in plain sight",body:"Channel performance isn't static. A channel that delivers quality leads for months can quietly degrade — and a buyer who increased spend based on past performance keeps losing money without knowing it.\n\nAt scale, this becomes structural. MarketingOS clients manage up to 2,000 channels simultaneously. High-volume channels get attention. Low-volume channels don't — even if their performance is collapsing. Weeks or months can pass before anyone notices."},
{lbl:"My Role",body:"Sole product designer on a cross-functional team (PM, engineers). Owned the feature end-to-end — from initial detection concept through popover design, filter system, and Channel Analysis interface."},
{lbl:"Solution",h:"Four phases of evolution",steps:[{n:"Phase 01",t:"Outlier Detection",d:"Algorithmic flagging identifying channels deviating from expected performance. First version: severity indicators surfaced inline, no extra interaction needed."},{n:"Phase 02",t:"Popover Insight",d:"A focused data-driven popover that explains exactly why a channel was flagged — which KPIs triggered it, how performance trended, and what action is recommended."},{n:"Phase 03",t:"Filters & Bulk Actions",d:"Infrastructure from Cross-Campaign Management enabled filters to zero in on flagged channels across the full account, and bulk actions to respond to a batch of outliers in one operation."},{n:"Phase 04",t:"Channel Analysis",d:"A dedicated interface moving buyers from reactive (responding to flags) to proactive — exploring channel performance, comparing trends, and making strategic allocation decisions before a problem surfaces."}]},
{lbl:"Detection",h:"The first indicator",body:"We started with a focused feature: algorithmic detection that flags channels deviating significantly from expected performance. Outliers surfaced inline — severity levels visible without any extra interaction. But clients were spending too much time interpreting the flags and deciding what to do next.",images:[{src:"assets/channel-analysis/web/image-2.webp",alt:"Channel outlier detection — inline indicators in the channels table"}]},
{lbl:"Popover Insight",h:"A focused, data-driven signal",body:"The key insight: clients didn't need more data — they needed the right data, in context. A popover surfaced a focused, explainable insight tied directly to the flagged channel: which KPIs triggered the flag, how performance trended over 14 and 30 days, and what action was recommended. Clients immediately understood both the signal and its basis.",images:[{src:"assets/channel-analysis/web/image-3.webp",alt:"Channel insight popover — KPI breakdown and performance trend"}]},
{lbl:"Filters & Actions",h:"From insight to action",body:"Using the selection and filtering infrastructure from Cross-Campaign Management, we added filters that let clients zero in on flagged channels across their entire account — instead of scanning campaign by campaign. Then: bulk actions that let a buyer respond to a batch of outliers in a single operation, compressing the time between detection and decision.",images:[{src:"assets/channel-analysis/web/image-4.webp",alt:"Filters for channel insights across the account"},{src:"assets/channel-analysis/web/image-5.webp",alt:"Bulk actions on outlier channels"}]},
{lbl:"Channel Analysis",h:"A dedicated analysis interface",body:"As the feature matured, outlier detection became the entry point for a broader capability. A dedicated Channel Analysis interface moved buyers from reactive to proactive — exploring channel performance across the account, comparing 14 and 30-day trends, and making strategic allocation decisions before a problem surfaced.",images:[{src:"assets/channel-analysis/web/image-6.webp",alt:"Channel Analysis — dedicated performance exploration interface"}]},
{lbl:"Process",h:"Built in dialogue with the client",body:"This feature evolved through a direct feedback loop built into the product itself. Early versions included thumbs up/down on each insight — and a thumbs down triggered a text comment request. Every piece of negative feedback was reviewed by the team, and recurring themes went back to the client for discussion.\n\nThis wasn't just user research — it was a validation mechanism embedded in the daily workflow. It told us which insights clients trusted, which confused them, and which they acted on. The popover format, the KPI selection, the recommendation language — all shaped by this loop.",images:[{src:"assets/channel-analysis/web/image-7.webp",alt:"Feature evolution through client dialogue"}]},
{lbl:"Impact",impacts:[{n:"Weeks→Hours",c:"g",l:"Detection time for\nchannel degradation"},{n:"2,000+",c:"a",l:"Channels under\nautomatic monitoring"},{n:"Daily",c:"b",l:"Frequency of use\nby media buyers"},{n:"$30M+",c:"g",l:"Platform media\nscaled — key driver"}]},
{lbl:"Reflection",reflection:"This project taught me that the hardest design problem isn't building a complex feature — it's knowing where to start. We could have built Channel Analysis from day one. Instead, we started with a single inline indicator and listened to what clients did next.\n\n<strong>The popover was the turning point.</strong> A small surface that made the whole system legible. Sometimes the most important design decision is the one that makes everything else make sense."}
]}
];

var CASE_BG=[
  'linear-gradient(135deg,#0a0f0a 0%,#0d1a0f 40%,#080808 100%)',
  'linear-gradient(135deg,#080d14 0%,#0a1220 40%,#080808 100%)',
  'linear-gradient(135deg,#100a08 0%,#1a0d08 40%,#080808 100%)',
  'linear-gradient(135deg,#0d0a14 0%,#120f1a 40%,#080808 100%)',
  'linear-gradient(135deg,#080d0d 0%,#0a1414 40%,#080808 100%)'
];
